version: "2.2"

services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - 4444:4444

  appium:
    image: appium/appium:v1.22.0-p0
    container_name: appium
    depends_on:
      - selenium-hub
    network_mode: "service:selenium-hub"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - $PWD/src/test/resources/apk:/root/tmp
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub

  android-container:
    image: budtmo/docker-android-x86-9.0
    container_name: android-9.0
    privileged: true
    scale: 1
    depends_on:
      - selenium-hub
      - appium
    ports:
      - 6080:6080
    volumes:
      - $PWD/src/test/resources/apk:/root/tmp/apk
    environment:
      - DEVICE=Samsung Galaxy S10
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium-hub

